language: node_js
node_js:
  - 10
  - node
cache:
  yarn: true
  directories:
    - .npm
branches:
  only:
    - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install: true
script:
  - yarn
  - yarn build

deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep_history: true
  # on:
  #   branch: master

# after_success:
#   - ./deploy.sh